import { MELO_CONTRACT_VERSION } from './contracts.js';

export const MELO_CAPABILITIES = {
  product: 'melo-game-creative-studio',
  contractVersion: MELO_CONTRACT_VERSION,
  mode: 'agent-operable',
  embeddedAgent: false,
  renderers: ['reference-2d', 'fixed-camera-cinematic', 'three-3d'],
  lockModes: ['frame-exact', 'semantic', 'rule-only'],
  assetOrigins: ['builtin', 'uploaded', 'generated', 'project', 'external-dcc'],
  pluginRuntimes: ['web-worker', 'node-worker', 'wasm'],
  commands: [
    'capabilities',
    'schema list',
    'schema get',
    'asset validate',
    'variant compile',
    'quality check',
    'material compile',
    'golden batch',
    'project migrate',
    'project scaffold',
    'authoring catalog',
    'skin list',
    'skin apply',
    'agent list',
    'agent run',
    'take validate',
    'document emit',
    'document compile',
    'produce',
    'render',
  ],
  notes: {
    'fixed-camera-cinematic': 'Available for locked 9:16 preview/export through the existing Three.js scene with Shot Profile, LookDev diagnostics and PBR runtime. Not a new engine.',
    headlessVideo: 'Node CLI does not encode pixels. `melo render` / `produce --render` spawn headless Chrome and WebCodecs; `rendered: true` only after an MP4 is written.',
    browserCapture: 'npm run capture:review uses headless Chrome to write native 2D frames and 1080×1920 silent MP4s. Software WebGL is not a GPU performance result.',
    videoLetterbox: '1064×1788 → 1080×1920 uses contain/letterbox only. This is a transitional reference-transfer mapping, not a finished 9:16 production profile.',
    diagnosticViews: 'world-normal, highlight-clip and bloom-contribution are proxy visualizations (flatShading / extra emissive / LDR output), not named G-buffer or HDR bloom buffers.',
    agentReplay: 'agent run / take validate emit GameReplayEnvelope JSON. GitHub Pages does not host the CLI; use a local or backend Node runtime.',
    authoring: 'project scaffold / skin apply / produce author levels and in-game skins. They do not replace Studio chrome. `produce --render` encodes only when Chrome is installed.',
    skills: 'skills/ wraps each CLI command so an external Agent can compose asset, take, render, and variant workflows.',
  },
} as const;
